CREATE SEQUENCE public.t_object_id_seq
	INCREMENT BY 1
	MINVALUE 10000
	MAXVALUE 99999
	START 10001
	CACHE 1
	CYCLE;

CREATE OR REPLACE FUNCTION public.generate_id()
 RETURNS bigint
 LANGUAGE sql
AS $BODY$SELECT CAST((TO_CHAR(now(), 'YYYYMMDDHH24MISS') || nextval('t_object_id_seq')) AS BIGINT);$BODY$